name: Smp
version: '${project.version}'
main: de.relativv.smp.main.Smp
api-version: 1.18
authors: [ relativv ]
description: A survival multiplayer plugin
commands:
  lifetransfer:
    description: Transfer your own lives to another
  life:
    description: Manage lives of all players
